replicaCount: 1

ingress:
  annotations:
    alb.ingress.kubernetes.io/load-balancer-name: "prod-internal-pibit-ai-alb"
    alb.ingress.kubernetes.io/group.name: prod-internal-alb

# Pod's node assignment
tolerations:
  - key: podType
    operator: Equal
    value: model
    effect: NoExecute
nodeSelector:
  podType: model
  lifecycle: Ec2OnDemand
affinity: {}

# Pod resources
resources:
  limits:
    # cpu: 3
    # memory: 7G
    nvidia.com/gpu: 1
  requests:
    # cpu: 3
    # memory: 5G
    nvidia.com/gpu: 1
