name: "CLA Assistant"
on:
  issue_comment:
    types: [created]
  pull_request_target:
    types: [opened,closed,synchronize]

jobs:
  CLA:
    runs-on: ubuntu-latest
    steps:
      - name: "CLA Assistant"
        if: (github.event.comment.body == 'recheck' || github.event.comment.body == 'I have read the CLA Document and I sign the CLA') || github.event_name == 'pull_request_target'
        # Beta Release
        uses: contributor-assistant/github-action@v2.2.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          PERSONAL_ACCESS_TOKEN: ${{ secrets.PERSONAL_ACCESS_TOKEN }}  # must be repository secret token
        with:
          path-to-signatures: 'signatures/version1/cla.json'
          path-to-document: 'https://github.com/cla-assistant/github-action/blob/master/SAPCLA.md' # e.g. a CLA or a DCO document
          branch: 'main'  # branch should not be protected
          allowlist: user1,bot*

          remote-organization-name: ultralytics
          remote-repository-name: cla
          #custom-notsigned-prcomment: 'pull request comment with Introductory message to ask new contributors to sign'
          custom-pr-sign-comment: 'I have read the CLA Document and I sign the CLA'
          custom-allsigned-prcomment: ✅ All Contributors have signed the CLA.
