# YOLOv5 🚀 by Ultralytics, GPL-3.0 license

name: Publish Docker Images

on:
  push:
    branches: master
  pull_request:
    branches: master

jobs:
  docker:
    name: Push Docker image to Docker Hub
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      #- name: Build and push M1/aarch64 image
      #  uses: docker/build-push-action@v3
      #  with:
      #    context: .
      #    platforms: linux/arm64
      #    file: utils/docker/Dockerfile-M1
      #    push: true
      #    tags: ultralytics/yolov5:latest-M1-pr

      - name: Build and push CPU image
        uses: docker/build-push-action@v3
        with:
          context: .
          file: utils/docker/Dockerfile-cpu
          push: true
          tags: ultralytics/yolov5:latest-cpu-pr

      - name: Build and push GPU image
        uses: docker/build-push-action@v3
        with:
          context: .
          file: utils/docker/Dockerfile
          push: true
          tags: ultralytics/yolov5:latest-pr
